---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# automater

<!-- badges: start -->
<!-- badges: end -->

The goal of automater is to automate boring stuff using R with various packages. 

## Installation

You can install the development version of automater.

```{r, eval = FALSE}
remotes::install_github("matutosi/automater")
```

## Example

See vignettes. 

https://github.com/matutosi/automater/tree/main/vignettes

- OCR with tesseract   
https://github.com/matutosi/automater/blob/main/vignettes/ocr_tesseract.md   

- Send outlook emails with Microsoft365R   
https://github.com/matutosi/automater/blob/main/vignettes/outlook_Microsoft365R.md   

- Set autofilter and freeze panel with xlsx   
https://github.com/matutosi/automater/blob/main/vignettes/xlsx.md   

- Translate with deeplr   
https://github.com/matutosi/automater/blob/main/vignettes/translate_deeplr.md


<!-- 
You'll still need to render `README.Rmd` regularly, to keep `README.md` up-to-date. 
`devtools::build_readme()` is handy for this. 
You could also use GitHub Actions to re-render `README.Rmd` every time you push. 
An example workflow can be found here: <https://github.com/r-lib/actions/tree/v1/examples>.
-->
