# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname locate_image
#' @param mt_1,mt_2  A matrix of image data.
#' @return  A logical.
#' @export
is_equal_matrix <- function(mt_1, mt_2) {
    .Call(`_automater_is_equal_matrix`, mt_1, mt_2)
}

#' Search needle image in haystack image and locate needle position.
#'
#' @rdname locate_image
#' @param ndl_mt,hay_mt  A matrix with grayscale x-y position.
#' @return  x-y position of needle image.
#'
#' @export
locate_image_cpp <- function(ndl_mt, hay_mt) {
    .Call(`_automater_locate_image_cpp`, ndl_mt, hay_mt)
}

